### ISSUE TITLE
Broken hex.pm support for private registries in latest version (v2.0.20250701035701)

### ISSUE THREAD

**Issue by bforchhammer** [dependabot/dependabot-core#12539]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Package ecosystem

mix

### dependabot.yml content

```
version: 2

registries:
  hex-organization-wooga:
    type: hex-organization
    organization: wooga
    key: "${{secrets.HEXPM_TOKEN}}"

updates:
  - package-ecosystem: mix
    directory: "/"
    # Required for custom registry, see https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#insecure-external-code-execution
    insecure-external-code-execution: allow
    open-pull-requests-limit: 10
    registries:
      - hex-organization-wooga
    schedule:
      interval: weekly
    labels:
      - dependencies
    # Only allow updates to the lockfile and ignore any version updates that affect mix.exs constraints
    versioning-strategy: lockfile-only
```

### What you expected to see, versus what you actually saw

We see the following error message in the dependabot updater logs.

```
 Dependabot can't resolve your Elixir dependency files
Dependabot failed to update your dependencies because there was an error resolving your Elixir dependency files.

Dependabot encountered the following error:

** (FunctionClauseError) no function clause matching in String.to_charlist/1    
    
    The following arguments were given to String.to_charlist/1:
    
        # 1
        nil
    
    Attempted function clauses (showing 1 out of 1):
    
        def to_charlist(+string+) when -is_binary(string)-
    
    (elixir 1.18.1) lib/string.ex:2861: String.to_charlist/1
    (hex 2.0.6) lib/hex/http/ssl.ex:65: Hex.HTTP.SSL.ssl_opts/1
    (hex 2.0.6) lib/hex/http.ex:47: Hex.HTTP.build_http_opts/2
    (hex 2.0.6) lib/hex/http.ex:19: Hex.HTTP.request/5
    /opt/hex/lib/run.exs:123: DependencyHelper.fetch_public_key/4
    /opt/hex/lib/run.exs:100: DependencyHelper.set_credentials/1
    /opt/hex/lib/run.exs:59: DependencyHelper.run/1
    /opt/hex/lib/run.exs:5: DependencyHelper.main/0
```

The log output shows that a number of "dependency_file_not_resolvable" errors, for many projects:
- from our `wooga` organization registry - all dependencies seem to be affected (ie. not able to update)
- some other dependencies are also not able to be updated (eg. `ecto_sql` in one run, https://hex.pm/packages/ecto_sql)

### Native package manager behavior

```
❯ mix deps.get
Resolving Hex dependencies...
Resolution completed in 0.59s
Unchanged:
  ...
  ecto_sql 3.13.1
  ...
```

```
❯ mix deps.update --all
Resolving Hex dependencies...
Resolution completed in 0.936s
Unchanged:
...
  plug 1.18.0
...
Upgraded:
...
  ecto_sql 3.13.1 => 3.13.2
...
* Updating ecto_sql (Hex package)
...
```

### Images of the diff or a link to the PR, issue, or logs

I wonder if the changes in this PR could be related, since it seems to be the only change to the dependabot/mix integration: https://github.com/dependabot/dependabot-core/pull/12419

**Comment by bforchhammer** [comment]
Additional information:

The last successful run was on this version:

```
  Pulling image ghcr.io/dependabot/dependabot-updater-mix:46303909e6d1235824728958d75313cc0c72be6d (attempt 1)...
  Successfully sent metric (dependabot.action.ghcr_image_pull) to remote API endpoint
  Pulled image ghcr.io/dependabot/dependabot-updater-mix:46303909e6d1235824728958d75313cc0c72be6d
  Pulling image ghcr.io/github/dependabot-update-job-proxy/dependabot-update-job-proxy:v2.0.20250618164131@sha256:be08bae568d8cd0269f06e45e742c1b8436f01a6eea00faa9c3c9f5ba52aa542 (attempt 1)...
  Successfully sent metric (dependabot.action.ghcr_image_pull) to remote API endpoint
  Pulled image ghcr.io/github/dependabot-update-job-proxy/dependabot-update-job-proxy:v2.0.20250618164131@sha256:be08bae568d8cd0269f06e45e742c1b8436f01a6eea00faa9c3c9f5ba52aa542
```


I tried creating+configuring a new hex.pm token but according to the hex.pm dashboard it has never been "used", ie. I'm suspecting that the credentials might not be attached properly on the api call to hex.pm when dependencies are checked?

**Comment by v-sachin-sandhu** [comment]
@bforchhammer , thanks for bringing this into notice, we are investigating the issue.

**Comment by Fraih001** [comment]
Confirming I am experiencing the same issue.

**Comment by v-sachin-sandhu** [comment]
Hello everyone 👋🏻 , 

We are completing scheduled work right now, this task is on priority list. We will start working on it as soon as possible, 

thank you for your patience.

**Comment by v-sachin-sandhu** [comment]
> Additional information:
> 
> The last successful run was on this version:
> 
> ```
>   Pulling image ghcr.io/dependabot/dependabot-updater-mix:46303909e6d1235824728958d75313cc0c72be6d (attempt 1)...
>   Successfully sent metric (dependabot.action.ghcr_image_pull) to remote API endpoint
>   Pulled image ghcr.io/dependabot/dependabot-updater-mix:46303909e6d1235824728958d75313cc0c72be6d
>   Pulling image ghcr.io/github/dependabot-update-job-proxy/dependabot-update-job-proxy:v2.0.20250618164131@sha256:be08bae568d8cd0269f06e45e742c1b8436f01a6eea00faa9c3c9f5ba52aa542 (attempt 1)...
>   Successfully sent metric (dependabot.action.ghcr_image_pull) to remote API endpoint
>   Pulled image ghcr.io/github/dependabot-update-job-proxy/dependabot-update-job-proxy:v2.0.20250618164131@sha256:be08bae568d8cd0269f06e45e742c1b8436f01a6eea00faa9c3c9f5ba52aa542
> ```
> 
> I tried creating+configuring a new hex.pm token but according to the hex.pm dashboard it has never been "used", ie. I'm suspecting that the credentials might not be attached properly on the api call to hex.pm when dependencies are checked?

Hi @bforchhammer , we are investigating this issue right now, below are the findings (also for record)

1. As you confirmed the last good version (thanks for that) was `46303909e6d1235824728958d75313cc0c72be6d`. this was released on **June 23**.
2. We released the last hex [changes](https://github.com/dependabot/dependabot-core/pull/12419) on **June 12**. So issue is not due to hex changes as we have also throughly investigated that credentials are passed along fine.
3. We did however [upgraded](https://github.com/dependabot/dependabot-core/pull/12542) Hex version to 2.2.1 on **July 1**. Do you recall when did you start noticing this issue? (as you also raised issue on same day we upgraded Hex version). We can try to downgrade to previous version and check if that fixes the issue.

**Comment by bforchhammer** [comment]
Thank you @sachin-sandhu  for looking into this! 

As an indication for the current state, here's a graph of all our dependabot jobs over the past 6 weeks for our internal repositories. You can see that we run updates on a weekly schedule, and that the last batch of dependabot updates actually ran a bit more successfully again, although some jobs did still fail. Please take the graph with a grain of salt, since it also includes jobs for `npm` and other package eco systems. We only recently started tracking this, ie. we unfortunately don't have data from before 6 weeks ago.

<img width="1258" height="474" alt="Image" src="https://github.com/user-attachments/assets/55bd53ed-46a1-47dd-9723-2e8b4aed8fd7" />

For one of our repositories:

<img width="1215" height="916" alt="Image" src="https://github.com/user-attachments/assets/1dc3558e-7a5c-4c0b-8335-8523ea3023ee" />

- Run 61 from a couple minutes ago was successful
- Run 60 from 3 weeks ago (July 14th) still experienced the `FunctionClauseError` issue reported above
- Run 55 from June 26th showed the `FunctionClauseError` for the first time
- Run 54, also from June 26th, ran successfully?

So...

- it seems that the issue was already there before the update on July 1st
- But it also looks like it might have disappeared somehow...?

If it helps I can try to collect more data points from other repositories beginning of next week.

**Comment by v-sachin-sandhu** [comment]
HI @bforchhammer ,
 
Thanks for detailed reply. 
Lets wait for next run to confirm whether issue resurfaces.

**Comment by bforchhammer** [comment]
This weeks runs seems to have gone mostly okay - at least I don't see the `FunctionClauseError` anymore.

We still have errors in the graph below, but these seem to be related to `npm/yarn` and a `path_dependencies_not_reachable` error for `file:../../../deps/phoenix`; I think this is a different issue.

<img width="1274" height="709" alt="Image" src="https://github.com/user-attachments/assets/9df7f555-a10e-436b-bc31-b1bf5ff8fec0" />

**Comment by v-sachin-sandhu** [comment]
@bforchhammer , 

Thank you for taking time to pull out the stats, I also checked in system and Hex errors are down (npm/yarn issues are not related to this). We are closing this issue.
