### ISSUE TITLE
Update existing multi-ecosystem PR rather than creating a new one

### ISSUE THREAD

**Issue by mudge** [dependabot/dependabot-core#12957]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Feature description

As mentioned in https://github.com/dependabot/dependabot-core/issues/12948, we're testing multi-ecosystem updates for a Rails application where we want a single PR raised weekly with both front-end (npm) and back-end (Bundler) dependency updates.

However, every Dependabot run will create a new PR if dependencies change (as they will week to week), e.g. `dependabot/all_dependencies-cc30755e31` and `dependabot/all_dependencies-abd6b84e54`. This leaves us in a strange situation where no one PR contains all the latest dependency updates for a group as the first might contain some npm and Bundler updates and the second only npm updates depending on what has been published.

Ideally, we'd like to be able to have Dependabot raise a single PR for a multi-ecosystem group (in our case, `all-dependencies`) and _update that existing PR_ on subsequent runs. That way, we only have a single PR to review and merge that contains the latest updates for a group rather than updates being spread across multiple PRs from separate runs.

**Comment by yeikel** [comment]
My understanding is that, in general, Dependabot tends to create new pull requests rather than updating existing ones. While groups behave somewhat differently due to the variety of changes, this pattern is still likely to remain unchanged.

> This leaves us in a strange situation where no one PR contains all the latest dependency updates for a group as the first might contain some npm and Bundler updates and the second only npm updates depending on what has been published.
> 

What you’re describing seems unusual. Dependabot is expected to create pull requests updating both groups to the latest versions, since each run checks for updates for both. 

Can you provide a way to reproduce this?

I’d classify this as a bug rather than intended behavior that should change

**Comment by mudge** [comment]
What information would be useful to reproduce this? I can provide a `Gemfile.lock` and a `yarn.lock` but the extra component here is that there were dependencies changed for both on one day and then dependency changes for npm alone on the second.

I can share the GitHub Actions logs for "Dependabot Updates"?

One thing that might also be worth mentioning is that the initial PR with both ecosystems (i.e. labelled with both "javascript" and "ruby") seemed to have become stuck in "⚠️ Dependabot is rebasing this PR ⚠️" (perhaps like https://github.com/dependabot/dependabot-core/issues/12903?).

**Comment by robaiken** [comment]
@mudge Thanks for reporting this! This bug is actually stemming from our group update feature. We're currently working on a fix for this exact issue where multiple prs are created instead of updating a single existing pr for multi-ecosystem groups.

We've merged a [foundational PR](https://github.com/dependabot/dependabot-core/pull/12911) that should address this problem. We're hoping to have this fully ready and deployed by the end of september.

Once this fix is live, you should see the behavior you're expecting - a single pr for your all-dependencies group that gets updated on subsequent runs rather than creating multiple separate prs.

**Comment by yeikel** [comment]
> [@mudge](https://github.com/mudge) Thanks for reporting this! This bug is actually stemming from our group update feature. We're currently working on a fix for this exact issue where multiple prs are created instead of updating a single existing pr for multi-ecosystem groups.
> 
> We've merged a [foundational PR](https://github.com/dependabot/dependabot-core/pull/12911) that should address this problem. We're hoping to have this fully ready and deployed by the end of september.
> 
> Once this fix is live, you should see the behavior you're expecting - a single pr for your all-dependencies group that gets updated on subsequent runs rather than creating multiple separate prs.

Thank you for confirming that it is indeed a bug

**Comment by Ark-kun** [comment]
Dependabot ignores existing group PRs even for single-ecosystem repos...

<img width="1678" height="308" alt="Image" src="https://github.com/user-attachments/assets/e487ead6-e005-4513-b6ce-95fab61cb54a" />

**Comment by eshgin-pactum** [comment]
any progress on this? I can still reproduce it. The job logs "Deferring creation of a new pull request. The existing pull request will update in a separate job" and exits green and that separate job hits the same branch.
