### ISSUE TITLE
npm version identifier "latest" not supported

### ISSUE THREAD

**Issue by Bertk** [dependabot/dependabot-core#1816]
Hi,

I got this error message because the version "latest" is used in a package.json file. We use this for private npm package from Azure DevOps artifacts npm repository.

```
/opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-npm_and_yarn-0.117.7/lib/dependabot/npm_and_yarn/requirement.rb:26:in `parse': Illformed requirement ["latest"] (Gem::Requirement::BadRequirementError)
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/requirement.rb:135:in `block in initialize'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/requirement.rb:135:in `map!'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/requirement.rb:135:in `initialize'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-npm_and_yarn-0.117.7/lib/dependabot/npm_and_yarn/requirement.rb:54:in `initialize'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-npm_and_yarn-0.117.7/lib/dependabot/npm_and_yarn/requirement.rb:45:in `new'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-npm_and_yarn-0.117.7/lib/dependabot/npm_and_yarn/requirement.rb:45:in `block in requirements_array'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-npm_and_yarn-0.117.7/lib/dependabot/npm_and_yarn/requirement.rb:43:in `map'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-npm_and_yarn-0.117.7/lib/dependabot/npm_and_yarn/requirement.rb:43:in `requirements_array'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.117.7/lib/dependabot/update_checkers/base.rb:267:in `block in version_from_requirements'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.117.7/lib/dependabot/update_checkers/base.rb:267:in `each'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.117.7/lib/dependabot/update_checkers/base.rb:267:in `flat_map'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.117.7/lib/dependabot/update_checkers/base.rb:267:in `version_from_requirements'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.117.7/lib/dependabot/update_checkers/base.rb:255:in `can_compare_requirements?'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.117.7/lib/dependabot/update_checkers/base.rb:246:in `requirements_up_to_date?'
	from /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/dependabot-common-0.117.7/lib/dependabot/update_checkers/base.rb:29:in `up_to_date?'
	from ./update.rb:75:in `block in <main>'
	from ./update.rb:66:in `each'
	from ./update.rb:66:in `<main>'

```

https://docs.npmjs.com/files/package.json#dependencies
check this sample from npm-package.json
```
{ "dependencies" :
  { "foo" : "1.0.0 - 2.9999.9999"
  , "bar" : ">=1.0.2 <2.1.2"
  , "baz" : ">1.0.2 <=2.3.4"
  , "boo" : "2.0.1"
  , "qux" : "<1.0.0 || >=2.3.1 <2.4.5 || >=2.5.2 <3.0.0"
  , "asd" : "http://asdf.com/asdf.tar.gz"
  , "til" : "~1.2"
  , "elf" : "~1.2.3"
  , "two" : "2.x"
  , "thr" : "3.3.x"
  , "lat" : "latest"
  , "dyl" : "file:../dyl"
  }
}
```

**Comment by feelepxyz** [comment]
@Bertk this should be fixed now 🎉  https://github.com/dependabot/dependabot-core/pull/3781

**Comment by jump912** [comment]
I have a similar error but the package versioning is not using the "latest" tag.

here is the error message:
```
/home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-e02718538024/npm_and_yarn/lib/dependabot/npm_and_yarn/requirement.rb:26:in `parse': Illformed requirement ["UI5-1.102"] (Gem::Requirement::BadRequirementError)
	from /usr/local/lib/ruby/3.1.0/rubygems/requirement.rb:138:in `block in initialize'
	from /usr/local/lib/ruby/3.1.0/rubygems/requirement.rb:138:in `map!'
	from /usr/local/lib/ruby/3.1.0/rubygems/requirement.rb:138:in `initialize'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-e02718538024/npm_and_yarn/lib/dependabot/npm_and_yarn/requirement.rb:54:in `initialize'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-e02718538024/npm_and_yarn/lib/dependabot/npm_and_yarn/requirement.rb:45:in `new'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-e02718538024/npm_and_yarn/lib/dependabot/npm_and_yarn/requirement.rb:45:in `block in requirements_array'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-e02718538024/npm_and_yarn/lib/dependabot/npm_and_yarn/requirement.rb:43:in `map'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-e02718538024/npm_and_yarn/lib/dependabot/npm_and_yarn/requirement.rb:43:in `requirements_array'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-e02718538024/common/lib/dependabot/update_checkers/base.rb:298:in `block in version_from_requirements'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-e02718538024/common/lib/dependabot/update_checkers/base.rb:298:in `each'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-e02718538024/common/lib/dependabot/update_checkers/base.rb:298:in `flat_map'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-e02718538024/common/lib/dependabot/update_checkers/base.rb:298:in `version_from_requirements'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-e02718538024/common/lib/dependabot/update_checkers/base.rb:286:in `can_compare_requirements?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-e02718538024/common/lib/dependabot/update_checkers/base.rb:273:in `requirements_up_to_date?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-e02718538024/common/lib/dependabot/update_checkers/base.rb:35:in `up_to_date?'
	from /home/dependabot/dependabot-updater/vendor/ruby/3.1.0/bundler/gems/dependabot-core-e02718538024/npm_and_yarn/lib/dependabot/npm_and_yarn/update_checker.rb:27:in `up_to_date?'
	from bin/update-script.rb:600:in `block in <main>'
	from bin/update-script.rb:563:in `each'
	from bin/update-script.rb:563:in `<main>'
##[error]The process '/usr/bin/docker' failed with exit code 1
```

Here is the the dependency:

```
"devDependencies": {
    "@sap/ux-specification": "UI5-1.102",
  },
```

I tried changing the version of "@sap/ux-specification" to "^1.102.0". the result is still the same.
