### ISSUE TITLE
Bazel support?

### ISSUE THREAD

**Issue by petemounce** [dependabot/dependabot-core#2196]
Hi there - we use [bazel](https://bazel.build) within our multi-product repos. It would be great to have dependabot understand and integrate with that?

Broadly, bazel is a cross-platform and cross-language build system. It wants one to specify all [external dependencies] within a [`WORKSPACE`] file within the root of the repo (with plans I think to allow [`WORKSPACE`] files, plural, within the repo).

A [`WORKSPACE`] file (and other Bazel files) is written in a language called [Starlark](https://docs.bazel.build/versions/master/skylark/language.html)

A [`WORKSPACE`] file can take dependencies as follows:

* on dependencies that are themselves built via bazel
* on dependencies _not_ built via bazel
* on dependencies packaged via that language's package manager (for details, the `bazelbuild/rules_*` repos)

A _great_ first addition would be to handle the `git_repository` and `http_archive` dependency rules, since _mostly_ these target github sha1s or tags.

I don't know which language dependabot itself is written in, but there is a [Starlark parser in golang](https://github.com/google/starlark-go) if it happens to be go.

[external dependencies]: https://docs.bazel.build/versions/master/external.html
[`WORKSPACE`]: https://docs.bazel.build/versions/master/build-ref.html#workspace

**Comment by chenrui333** [comment]
Any update on this thread?

**Comment by cpsauer** [comment]
Not dependabot, but solving the same need: I worked with the [renovate](https://github.com/renovatebot/renovate) author to get things in good working shape for Bazel. It's now doing a great job auto-updating our GitHub-hosted dependencies. I'd recommend giving Renovate a try, if you're trying to automate Bazel dependency updates.

(I'd originally followed this issue long ago, hoping dependabot would add Bazel support.)

**Comment by chenrui333** [comment]
I have not worked with renovate before, should I be concerned about its introduction into corporate usage?

**Comment by rkhir** [comment]
> > there is a Starlark parser in golang if it happens to be go.
> 
> It might be worth pointing out that [Skylark is a subset of Python 3](https://docs.bazel.build/versions/master/skylark/language.html) as that might simplify parsing of the `WORKSPACE` file.
> 
> I have a Bazel project where I'm interested in enabling dependabot. I _considered_ 1) writing a script that generate a `pom.xml` from the `WORKSPACE` file to hack around the lack of support and 2) adding a CI check that make sure that the `pom.xml` file is synced with `WORKSPACE`. This would obviously mean that no submitted pull requests by dependabot would work, but at least we'd know of security issues. Maybe too hacky, haven't decided...

@JensRantil, great Idea. although Bazel does support the `pom.xml` generation part of [this rule](https://github.com/bazelbuild/rules_jvm_external/tree/master/examples/pom_file_generation) the file can be synced on each `bazel build ...` command, which will save the implementer a few steps. 🍻

**Comment by dmivankov** [comment]
Can confirm that for maven/java/scala dependencies the approach of generating pom.xml and putting it into repository works. As a convenience you may want to have scripts/command to convert between bzl and pom
- put (sorted) list of artifact names into separate .bzl file
- script to generate pom from rule mentioned above (for PRs updating .bzl file)
- script to generate .bzl file from .pom file via for example xslt transformation (for dependabot or other PRs updating .pom file)
- bazel test to check that .pom file matches .bzl targets
- bazel test to check that .bzl file matches from-pom-generation script output

**Comment by petemounce** [comment]
@feelepxyz friendly ping in hope of an update?

**Comment by feelepxyz** [comment]
@petemounce 👋  I'm no longer working on Dependabot so not sure what the current plans are.

cc @exvuma as pm for Dependabot who might be able to answer.

**Comment by hcoona** [comment]
@exvuma ping

**Comment by ztl8702** [comment]
With [bzlmod](https://bazel.build/build/bzlmod) being generally available, maybe this issue's scope can be changed to:
* keeping `bazel_dep`s in `MODULE.bzl` up to date

?

**Comment by cpsauer** [comment]
^ I think maybe in addition. I'm guessing it'll be a good while before WORKSPACE goes away.

**Comment by mihaimaruseac** [comment]
Bzlmod is easier to parse than WORKSPACE. With bzlmod, this will be a tractable amount of work, but with WORKSPACE it's not as easy as each project can have their own method of specifying dependencies, including having multiple macros/functions in the same file.

E.g., TensorFlow has separate files where the dependencies are actually mentioned given the needs of downstream projects. https://github.com/tensorflow/tensorflow/blob/3416f491d8a571bf6bac142b48cd70ad07518c21/WORKSPACE Bzlmod would simplify this a lot

**Comment by romanowski** [comment]
We have a new alternative: [Bazel Steward](https://github.com/marketplace/actions/bazel-steward). It is an open-source bot to update dependencies dedicated to Bazel projects. It runs Bazel under the hood to extract dependencies, so it should work with most setups, including custom ones. 

For now, it supports only maven dependencies, Bazel version, and version of Bazel rules, but there are plans to add support for NPM, go modules, and more.

**Comment by meteorcloudy** [comment]
renovatebot has already added support for Bzlmod: https://github.com/renovatebot/renovate/issues/13658

**Comment by albertocavalcante** [comment]
Despite the above options, would still be great to see this implemented in Dependabot as well. Just to add, support for Bazel upgrades through Bazelisk would be appreciated.

And it's not clear to me: is this feature request being considered?

**Comment by robaiken** [comment]
Hello everyone!

We're excited to announce that we're beginning work on Bazel support in Dependabot. We want to make sure this integration is as useful as possible for your projects, so we'd love to hear your feedback on a few key questions:

**1. Which would be most valuable for your projects: `MODULE.bazel` or `WORKSPACE` support?**
**2. Are there any specific Bazel dependency update patterns or edge cases we should consider?**

Your insights and examples will help guide our development process and ensure we deliver the features your teams need most.

Thank you for helping shape Dependabot's Bazel integration!

**Comment by prestonvanloon** [comment]
1) Our project has not yet migrated to bzlmod. We will likely delay bzlmod until bazel 7 LTS reaches EOL in december 2026.
2) Most of our dependencies are not in the WORKSPACE file, but loaded in a deps.bzl via gazelle. 

Our project is https://github.com/OffchainLabs/prysm

**Comment by phlax** [comment]
we (https://github.com/envoyproxy/envoy) currently implement our own dep management for bazel 

we are likewise still using WORKSPACE but are tentatively trying to move over to bzlmod

our issue tracking is for non-transitive deps and we have workflows for generating pr updates

on the dependency parsing side we export bazel config to json, and for updating the deps we have some very hacky custom shell scripts

while it would be great to have external management for this - if im honest im not sure the workspace model works well for generic dep management as it can be configured so many different ways - so would be happy if this just targeted bzlmod

**Comment by daniel-b2c2** [comment]
> We're excited to announce that we're beginning work on Bazel support in Dependabot.

Awesome! Let me provide some feedback. I will edit and expand my response over the next few hours.
  
> 1. Which would be most valuable for your projects: MODULE.bazel or WORKSPACE support?

I really wouldn't start with `WORKSPACE`,  it's deprecated in version 7 which is EOS in 2026, and it's unsupported in Bazel version 8 which is the active version. `MODULE.bazel` would add long term value and everyone in the comments section that wants `WORKSPACE` will probably migrate to the modular approach when forced to do so.

> 2. Are there any specific Bazel dependency update patterns or edge cases we should consider?

In addition to the `MODULE.bazel` which defines the Bazel module dependencies (or legacy WORKSPACE), there are language specific inputs and output files as Bazel is a polyglot system. 

I'm working with Java, so a java project if you want to retrieve dependencies via the maven ecosystem you will most likely be using the [rules_jvm_external](https://github.com/bazel-contrib/rules_jvm_external) module and will have corresponding files where you declare Java dependencies as well as the lock file.

My current project has a `maven_deps.MODULE.bazel`, the prefix `maven_deps` is arbitrary as it's referenced by the root module.

Here's a sample of it where we define classic maven dependencies
```
maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    name = "maven",
    artifacts = [
        "args4j:args4j:2.37",
        "com.auth0:java-jwt:4.5.0",
        "com.dslplatform:dsl-json:2.0.2",
        "io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.122.Final",
        "org.apache.flink:flink-streaming-java:jar:tests:1.20.1",
    ],
    fetch_sources = True,
    lock_file = "//:maven_install.json",
    repositories = [
        # we should now be able to pull all dependencies via maven-virtual
        "https://mycompany.jfrog.io/artifactory/maven-virtual",
    ],
    fail_if_repin_required = True,
    version_conflict_policy = "pinned",
)
```

Note how this references a lock_file located at `maven_install.json` and how the `fail_if_repin_required` is on. Crucially when dependencies are updated, the lock file should regenerated, as a common pattern is to fail builds if lock file is not synchronised. Note that this is optional but highly recommended - more than ever following the recent supply chain NPM fiasco. 

Note the '5-arity' dependency in netty where we specify the platform and classifier.

[I will edit this post to be more specific and give examples shortly]

I'll be honest, in the Java world, supporting the rules_jvm_external module's inputs and outputs is really where the value is. As this is where actual library dependencies for our apps are stored.

**Comment by robaiken** [comment]
@daniel-b2c2 Thank you for the feedback! To ensure we build Bazel support that covers real-world use cases, we'd love some help from the community. If you're willing, could you share example repositories or minimal reproducible examples that demonstrate the dependency patterns you use?

Having concrete examples would help us test our implementation, handle edge cases correctly, and prioritize features based on what you actually need. You can share by linking to a public repo. Thank you!

**Comment by cpovirk** [comment]
I gave my thumbs up to the post by @daniel-b2c2, so here's our example of `rules_jvm_external` in bzlmod:

https://github.com/google/bazel-common/blob/master/MODULE.bazel

(I'd be fine with getting rid of constants like `GUAVA_VERSION` once we have a tool like Dependabot that is automatically keeping everything up to date.)

**Comment by robaiken** [comment]
The Bazel updater is now available in beta! To enable it, add the following to your `dependabot.yml` configuration:

```yaml
enable-beta-ecosystems: true # Required to use the Bazel ecosystems
updates:
  - package-ecosystem: "bazel" 
    directory: "/" # Location of package manifests
```

**Important notes:**

* Make sure to include `enable-beta-ecosystems: true` in your config, otherwise the Bazel updater won't be activated
* Supports `WORKSPACE` and `MODULE.bazel` files
* Updating lock files is currently not available

Please let me know if you encounter any errors or issues during your feedback is very important to us!

**Comment by alexeagle** [comment]
Awesome! @robaiken can you easily add `*.MODULE.bazel`? See https://github.com/bazelbuild/buildtools/pull/1266 for links to context.

**Comment by robaiken** [comment]
Thanks @alexeagle, I'll add that to the roadmap

**Comment by robaiken** [comment]
@alexeagle Do you have an example repo with `*.MODULE.bazel` files that I can use to test against?

**Comment by Ahajha** [comment]
Just wanted to say I'm already trial running this, so far so good, lockfiles and *.MODULE.bazel would be super helpful (in that order preferably :) ) Thanks for getting this going!

**Comment by keith** [comment]
here's a repo with a `*.MODULE.bazel` file https://github.com/modular/modular/blob/5f4f3eebab0c70803747829fbf8dfdc728999edb/bazel/common.MODULE.bazel

**Comment by robaiken** [comment]
@alexeagle @Ahajha @keith `*.MODULE.bazel` and lockfile support is now live! Let us know what you think!

**Comment by dhalperi** [comment]
FYI @robaiken, I'm having a hard time getting it to work with my projects. They typically fail at some bazel error I don't get in normal CI builds

* https://github.com/batfish/batfish/network/updates/27123245/jobs
```
ERROR: /home/dependabot/.cache/bazel/_bazel_dependabot/0bd3c3a13404afb561b1749cf8d4cfbc/external/rules_jvm_external+/private/extensions/maven.bzl:722:52: Traceback (most recent call last):
	File "/home/dependabot/.cache/bazel/_bazel_dependabot/0bd3c3a13404afb561b1749cf8d4cfbc/external/rules_jvm_external+/private/extensions/maven.bzl", line 722, column 52, in maven_impl
		lock_file_content = mctx.read(mctx.path(repo.get("lock_file")))
Error in path: Unable to load package for //:maven_install.json: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - 
ERROR: /home/dependabot/.cache/bazel/_bazel_dependabot/0bd3c3a13404afb561b1749cf8d4cfbc/external/rules_python+/python/private/pypi/parse_requirements.bzl:93:28: Traceback (most recent call last):
	File "/home/dependabot/.cache/bazel/_bazel_dependabot/0bd3c3a13404afb561b1749cf8d4cfbc/external/rules_python+/python/private/pypi/extension.bzl", line 366, column 25, in _pip_impl
		mods = parse_modules(module_ctx, enable_pipstar = rp_config.enable_pipstar)
	File "/home/dependabot/.cache/bazel/_bazel_dependabot/0bd3c3a13404afb561b1749cf8d4cfbc/external/rules_python+/python/private/pypi/extension.bzl", line 256, column 30, in parse_modules
		builder.pip_parse(
	File "/home/dependabot/.cache/bazel/_bazel_dependabot/0bd3c3a13404afb561b1749cf8d4cfbc/external/rules_python+/python/private/pypi/hub_builder.bzl", line 58, column 47, in lambda
		pip_parse = lambda *a, **k: _pip_parse(self, *a, **k),
	File "/home/dependabot/.cache/bazel/_bazel_dependabot/0bd3c3a13404afb561b1749cf8d4cfbc/external/rules_python+/python/private/pypi/hub_builder.bzl", line 125, column 22, in _pip_parse
		_create_whl_repos(
	File "/home/dependabot/.cache/bazel/_bazel_dependabot/0bd3c3a13404afb561b1749cf8d4cfbc/external/rules_python+/python/private/pypi/hub_builder.bzl", line 383, column 50, in _create_whl_repos
		requirements_by_platform = parse_requirements(
	File "/home/dependabot/.cache/bazel/_bazel_dependabot/0bd3c3a13404afb561b1749cf8d4cfbc/external/rules_python+/python/private/pypi/parse_requirements.bzl", line 93, column 28, in parse_requirements
		contents = ctx.read(file)
Error in read: Unable to load package for //python:requirements.txt: BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
 - python
ERROR: error evaluating module extension @@rules_jvm_external+//:extensions.bzl%maven
ERROR: error evaluating module extension @@rules_python+//python/extensions:pip.bzl%pip
ERROR: Failed to process 2 extensions due to errors.
```

I had this same error in a test repo I set up, but upgrading some rules and qualifying the lock file seemed to do the trick: https://github.com/dhalperi/dependabot-bazel-test/commit/2abcdf91342a7feb3e946e81e02ea94d6422765c
But that's already been done in batfish/batfish as far as I can tell.

P.S. I am happy to try to debug myslef; I couldn't figure out where those quoted lines came from.

**Comment by markhallen** [comment]
> FYI [@robaiken](https://github.com/robaiken), I'm having a hard time getting it to work with my projects. They typically fail at some bazel error I don't get in normal CI builds
> 
> * https://github.com/batfish/batfish/network/updates/27123245/jobs
> 
> 
> I had this same error in a test repo I set up, but upgrading some rules and qualifying the lock file seemed to do the trick: [dhalperi/dependabot-bazel-test@2abcdf9](https://github.com/dhalperi/dependabot-bazel-test/commit/2abcdf91342a7feb3e946e81e02ea94d6422765c) But that's already been done in batfish/batfish as far as I can tell.
> 
> P.S. I am happy to try to debug myslef; I couldn't figure out where those quoted lines came from.

Thanks for reporting this @dhalperi. This should be fixed by https://github.com/dependabot/dependabot-core/pull/13528

**Comment by rasberik** [comment]
Hi! Thanks for moving this forward. I wanted to ask if / how to make this work with `*.bzl` files that define dependencies macros using `http_archive` etc. Similar to [here](https://github.com/bazelbuild/bazel/blob/e697ff774eff6c8a708fffca6fd8eeeb7f468bfe/repositories.bzl#L138).

I tried to provide paths to their directories, but it didnt seem to recognize.

For remaining MODULE deps, it worked great except not respecting the ignore "version-update:semver-major" part, but thats not major issue at the moment.

**Comment by dhalperi** [comment]
Q: should we expect it to read the java deps in maven_install.json files and suggest upgrades to them? I'm not seeing it in the logs.

**Comment by robaiken** [comment]
@dhalperi We're only updating Bazel deps. I've looked into updating Bazel ecosystem integrations, but I'm concerned about scope creep and can't guarantee we'll support it. There are a bunch of ecosystem integrations out there, and if we start supporting the current ones, we'll probably end up needing to support future ones too

**Comment by Vertexwahn** [comment]
I see the issues that Dependabot tries to "upgrade" from `libpng@1.6.50.bcr.1` to  `libpng@1.6.50`. The Problem here is that `.bcr.1` indicates that there was a problem with `1.6.50` and since existing BCR module versions are not allowed to change an artificial `.bcr.1` version postfix is introduced. This is a common pattern within BCR. Imaging support for Windows is added - it will become `.bcr.2`. A linker problem on macOS ARM is fixed ->  `.bcr.3`, etc. stuff we did not get right the first time becomes `.bcr.X` by just counting up. Hence `libpng@1.6.50.bcr.1` is newer and better than `libpng@1.6.50`, and no update should be proposed.

Neverthless, this goes into the right direction! Thanks for the work @petemounce!

**Comment by dhalperi** [comment]
Another BCR oddity:

Link: https://github.com/batfish/batfish/actions/runs/19447742472/job/55646024677

```text
updater | 2025/11/17 23:11:48 INFO <job_1155707803> Checking if rules_python 1.6.3 needs updating
  proxy | 2025/11/17 23:11:48 [255] GET [https://api.github.com:443/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python](https://api.github.com/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python)
2025/11/17 23:11:48 [255] * authenticating github api request with token for api.github.com
  proxy | 2025/11/17 23:11:48 [255] 200 [https://api.github.com:443/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python](https://api.github.com/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python)
  proxy | 2025/11/17 23:11:48 [257] GET [https://api.github.com:443/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python](https://api.github.com/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python)
2025/11/17 23:11:48 [257] 200 [https://api.github.com:443/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python](https://api.github.com/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python) (cached)
  proxy | 2025/11/17 23:11:48 [259] GET [https://api.github.com:443/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python](https://api.github.com/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python)
2025/11/17 23:11:48 [259] 200 [https://api.github.com:443/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python](https://api.github.com/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python) (cached)
updater | 2025/11/17 23:11:48 INFO <job_1155707803> Latest version is 1.7.0-rc4
updater | 2025/11/17 23:11:48 INFO <job_1155707803> Pull request #9606 already exists for rules_python with latest version 1.7.0-rc4
  proxy | 2025/11/17 23:11:48 [261] POST /update_jobs/1155707803/record_ecosystem_meta
```

The one that stands out to me is the `(cached)` hit on the API requests.

I'm surprised it's not seeing that 1.7.0 final is released, much less 1.7.0-r6 or -r5. Seems to imply that the cache is 2 weeks old (r5 was released November 5th). They're at the URL now: https://api.github.com/repos/bazelbuild/bazel-central-registry/contents/modules/rules_python

**Comment by dtschiffman** [comment]
I'm trying to set this up, but it's failing on every dependency with "BUILD file not found" errors.

The MODULE.bazel in question uses the include() directive to split the file into multiple segments:

```bazel
  include("//some/path:file.MODULE.bazel")
  include("//another/path:dependencies.MODULE.bazel")
  # ... etc
```

When Dependabot runs, it errors out with:
```
ERROR: unable to load package for '//some/path:file.MODULE.bazel' included at dependabot_tmp_dir/MODULE.bazel:27:1: 
BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
```

From what I can tell, Dependabot copies the main MODULE.bazel to a temporary directory but doesn't bring along the included *.MODULE.bazel files or set up the directory structure that Bazel needs to resolve those labels. 

Is there something I'm missing in the configuration, or does Dependabot not support the include() directive yet?

**Comment by dhalperi** [comment]
Re caching, looks like the headers say only 60s so I'm not sure hwy it would be using 2 weeks old cache...

```
Warning! Q CLI is now Kiro CLI and should be invoked as kiro-cli rather than q

⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀     ⢀⣴⣶⣶⣦⡀⠀⠀⠀⢀⣴⣶⣦⣄⡀⠀⠀⢀⣴⣶⣶⣦⡀⠀⠀⢀⣴⣶⣶⣶⣶⣶⣶⣶⣶⣶⣦⣄⡀⠀⠀⠀⠀⠀⠀⢀⣠⣴⣶⣶⣶⣶⣶⣦⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀    ⢰⣿⠋⠁⠈⠙⣿⡆⠀⢀⣾⡿⠁⠀⠈⢻⡆⢰⣿⠋⠁⠈⠙⣿⡆⢰⣿⠋⠁⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠻⣦⠀⠀⠀⠀⣴⡿⠟⠋⠁⠀⠀⠀⠈⠙⠻⢿⣦⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀    ⢸⣿⠀⠀⠀⠀⣿⣇⣴⡿⠋⠀⠀⠀⢀⣼⠇⢸⣿⠀⠀⠀⠀⣿⡇⢸⣿⠀⠀⠀⢠⣤⣤⣤⣤⣄⠀⠀⠀⠀⣿⡆⠀⠀⣼⡟⠀⠀⠀⠀⣀⣀⣀⠀⠀⠀⠀⢻⣧⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀    ⢸⣿⠀⠀⠀⠀⣿⡿⠋⠀⠀⠀⢀⣾⡿⠁⠀⢸⣿⠀⠀⠀⠀⣿⡇⢸⣿⠀⠀⠀⢸⣿⠉⠉⠉⣿⡇⠀⠀⠀⣿⡇⠀⣼⡟⠀⠀⠀⣰⡿⠟⠛⠻⢿⣆⠀⠀⠀⢻⣧⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀    ⢸⣿⠀⠀⠀⠀⠙⠁⠀⠀⢀⣼⡟⠁⠀⠀⠀⢸⣿⠀⠀⠀⠀⣿⡇⢸⣿⠀⠀⠀⢸⣿⣶⣶⡶⠋⠀⠀⠀⠀⣿⠇⢰⣿⠀⠀⠀⢰⣿⠀⠀⠀⠀⠀⣿⡆⠀⠀⠀⣿⡆
⠀⠀⠀⠀⠀⠀⠀    ⢸⣿⠀⠀⠀⠀⠀⠀⠀⠀⠹⣷⡀⠀⠀⠀⠀⢸⣿⠀⠀⠀⠀⣿⡇⢸⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣼⠟⠀⢸⣿⠀⠀⠀⢸⣿⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⣿⡇
⠀⠀⠀⠀⠀⠀⠀    ⢸⣿⠀⠀⠀⠀⠀⣠⡀⠀⠀⠹⣷⡄⠀⠀⠀⢸⣿⠀⠀⠀⠀⣿⡇⢸⣿⠀⠀⠀⠀⣤⣄⠀⠀⠀⠀⠹⣿⡅⠀⠀⠸⣿⠀⠀⠀⠸⣿⠀⠀⠀⠀⠀⣿⠇⠀⠀⠀⣿⠇
⠀⠀⠀⠀⠀⠀⠀    ⢸⣿⠀⠀⠀⠀⣾⡟⣷⡀⠀⠀⠘⣿⣆⠀⠀⢸⣿⠀⠀⠀⠀⣿⡇⢸⣿⠀⠀⠀⠀⣿⡟⣷⡀⠀⠀⠀⠘⣿⣆⠀⠀⢻⣧⠀⠀⠀⠹⣷⣦⣤⣤⣾⠏⠀⠀⠀⣼⡟
⠀⠀⠀⠀⠀⠀⠀    ⢸⣿⠀⠀⠀⠀⣿⡇⠹⣷⡀⠀⠀⠈⢻⡇⠀⢸⣿⠀⠀⠀⠀⣿⡇⢸⣿⠀⠀⠀⠀⣿⡇⠹⣷⡀⠀⠀⠀⠈⢻⡇⠀⠀⢻⣧⠀⠀⠀⠀⠉⠉⠉⠀⠀⠀⠀⣼⡟
⠀⠀⠀⠀⠀⠀⠀    ⠸⣿⣄⡀⢀⣠⣿⠇⠀⠙⣷⡀⠀⢀⣼⠇⠀⠸⣿⣄⡀⢀⣠⣿⠇⠸⣿⣄⡀⢀⣠⣿⠇⠀⠙⣷⡀⠀⠀⢀⣼⠇⠀⠀⠀⠻⣷⣦⣄⡀⠀⠀⠀⢀⣠⣴⣾⠟
⠀⠀⠀⠀⠀⠀⠀    ⠀⠈⠻⠿⠿⠟⠁⠀⠀⠀⠈⠻⠿⠿⠟⠁⠀⠀⠈⠻⠿⠿⠟⠁⠀⠀⠈⠻⠿⠿⠟⠁⠀⠀⠀⠈⠻⠿⠿⠟⠁⠀⠀⠀⠀⠀⠈⠙⠻⠿⠿⠿⠿⠟⠋⠁


╭──────────────────────────────────────────────────────────────────────────────╮
│ Amazon Q Developer CLI is now the Kiro CLI. The Kiro CLI leverages the       │
│ agentic features of Amazon Q Developer CLI and is fully compatible with it.  │
│ Learn more: https://kiro.dev/cli                                             │
╰──────────────────────────────────────────────────────────────────────────────╯


Model: Auto (/model to change)


> What cache headaers does https://api.github.com/repos/bazelbuild/bazel-central-registry/contents/modules/rules_jvm_external return?

> I'll check the cache headers returned by that GitHub API endpoint.
I will run the following command: curl -sI "https://api.github.com/repos/bazelbuild/bazel-central-registry/contents/modules/rules_jvm_external" | grep -i cache (using tool: shell)
Purpose: Fetch HTTP headers and filter for cache-related headers


Allow this action? Use 't' to trust (always allow) this tool for the session. [y/n/t]:

> y

cache-control: public, max-age=60, s-maxage=60
 - Completed in 0.190s

> The GitHub API returns this cache header:

cache-control: public, max-age=60, s-maxage=60


This means:
- public - response can be cached by any cache (browser, CDN, etc.)
- max-age=60 - response is fresh for 60 seconds in private caches
- s-maxage=60 - response is fresh for 60 seconds in shared caches (CDNs)

So the content is cached for 1 minute before it needs to be revalidated.
 ▸ Time: 16s
```

**Comment by markhallen** [comment]
> I'm trying to set this up, but it's failing on every dependency with "BUILD file not found" errors.
> 
> The MODULE.bazel in question uses the include() directive to split the file into multiple segments:
> 
>   include("//some/path:file.MODULE.bazel")
>   include("//another/path:dependencies.MODULE.bazel")
>   # ... etc
> When Dependabot runs, it errors out with:
> 
> ```
> ERROR: unable to load package for '//some/path:file.MODULE.bazel' included at dependabot_tmp_dir/MODULE.bazel:27:1: 
> BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
> ```
> 
> From what I can tell, Dependabot copies the main MODULE.bazel to a temporary directory but doesn't bring along the included *.MODULE.bazel files or set up the directory structure that Bazel needs to resolve those labels.
> 
> Is there something I'm missing in the configuration, or does Dependabot not support the include() directive yet?

We merged #13586 today that should fix this behavior @dtschiffman

**Comment by markhallen** [comment]
> Hi! Thanks for moving this forward. I wanted to ask if / how to make this work with `*.bzl` files that define dependencies macros using `http_archive` etc. Similar to [here](https://github.com/bazelbuild/bazel/blob/e697ff774eff6c8a708fffca6fd8eeeb7f468bfe/repositories.bzl#L138).
> 
> I tried to provide paths to their directories, but it didnt seem to recognize.
> 
> For remaining MODULE deps, it worked great except not respecting the ignore "version-update:semver-major" part, but thats not major issue at the moment.

We merged #13586 today that should address this @rasberik

**Comment by robaiken** [comment]
Thank you to everyone who participated in beta testing Bazel support for Dependabot!

**Bazel charts support is now generally available. To use it:**

1. Remove `enable-beta-ecosystems: true` from your dependabot.yml files
2. Add Bazel as a package ecosystem:

```yaml
version: 2
updates:
  - package-ecosystem: "bazel"
    directory: "/"
    schedule:
      interval: "weekly"
```

If you encounter any issues, please log them as [new issues](https://github.com/dependabot/dependabot-core/issues)!

Thanks again for your support!

**Comment by dhalperi** [comment]
Split off my caching issue to https://github.com/dependabot/dependabot-core/issues/13624

**Comment by dtschiffman** [comment]
> > I'm trying to set this up, but it's failing on every dependency with "BUILD file not found" errors.
> > The MODULE.bazel in question uses the include() directive to split the file into multiple segments:
> > include("//some/path:file.MODULE.bazel")
> > include("//another/path:dependencies.MODULE.bazel")
> > # ... etc
> > When Dependabot runs, it errors out with:
> > ```
> > ERROR: unable to load package for '//some/path:file.MODULE.bazel' included at dependabot_tmp_dir/MODULE.bazel:27:1: 
> > BUILD file not found in any of the following directories. Add a BUILD file to a directory to mark it as a package.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > From what I can tell, Dependabot copies the main MODULE.bazel to a temporary directory but doesn't bring along the included *.MODULE.bazel files or set up the directory structure that Bazel needs to resolve those labels.
> > Is there something I'm missing in the configuration, or does Dependabot not support the include() directive yet?
> 
> We merged [#13586](https://github.com/dependabot/dependabot-core/pull/13586) today that should fix this behavior [@dtschiffman](https://github.com/dtschiffman)

@markhallen the pr you linked does not seem to support include statements, so the issue I have still exists. I will open as a new issue here: https://github.com/dependabot/dependabot-core/issues/13676

**Comment by corneliusroemer** [comment]
You can unpin this issue now as it's completed
