### ISSUE TITLE
Update correctly go.sum in case of several modules in the same project with references between them

### ISSUE THREAD

**Issue by mmorel-35** [dependabot/dependabot-core#4124]
**Package ecosystem**
gomod
**Package manager version**

**Language version**

**Manifest location and content prior to update**
`/go.mod` (module gocloud.dev)
`/pubsub/kafkapubsub/go.mod`(module gocloud.dev/pubsub/kafkapubsub) contains
```
replace gocloud.dev => ../../
```

**dependabot.yml content**
```
version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /pubsub/kafkapubsub
    schedule:
      interval: weekly
```

**Updated dependency**
github.com/aws/aws-sdk-go@v1.40.16

**What you expected to see, versus what you actually saw**
```
******************************
* Running Go tests for module: pubsub/kafkapubsub
******************************
go: gocloud.dev@v0.23.0 requires
	github.com/aws/aws-sdk-go@v1.40.16: missing go.sum entry; to add it:
	go mod download github.com/aws/aws-sdk-go
```

I would like to see the go.sum updated appropriately when there are references between several modules in the same project.
**Native package manager behavior**

**Images of the diff or a link to the PR, issue or logs**

**🕹 Bonus points: Smallest manifest that reproduces the issue**

**Comment by jeffwidman** [comment]
https://github.com/dependabot/dependabot-core/pull/5983 fixed a similar issue and may have fixed this as well since it allows `go mod tidy` to proceed, which should in turn update `go.sum` (at least I _think_ that's what happens).

@mmorel-35 can you test this again and see if it's fixed now?

**Comment by jeffwidman** [comment]
👋 @mmorel-35 haha, fancy seeing you on this repo too after I just saw you over on https://github.com/vishvananda/netns/pull/68 (thanks for that BTW!)

Can you check whether ☝️ fixed this for you?

**Comment by mmorel-35** [comment]
Hi @jeffwidman !
Nice to see you here, too !
I don’t think it’s fixed.

I just tried it on a fork of consul , see 
https://github.com/mmorel-35/consul/pull/24/files

With the update of github.com/stretchr/testify to 1.8.1 in the sdk/go.mod , I’m expecting to see an update of api/go.sum
But it’s not the case
