### ISSUE TITLE
Dependabot environment variables

### ISSUE THREAD

**Issue by trent-abc** [dependabot/dependabot-core#4660]
I would like to specify an environment variable during dependabot runs.

I'm attempting to authenticate against a private cloudsmith python repository.  I arrived at a working configuration [here](https://github.com/dependabot/dependabot-core/issues/4539).  However, this working configuration means my Pipfile looks like so:

```
[[source]]
url = "https://dl.cloudsmith.io/basic/company/repo/python/index/"
verify_ssl = true
name = "cloudsmith"
```

While this works for dependabot given the yml in the aforementioned ticket, it doesn't work for local development.  For local development our pipfile looks like so:

```
[[source]]
url = "https://dl.cloudsmith.io/${CLOUDSMITH_KEY}/company/repo/python/index/"
verify_ssl = true
name = "cloudsmith"
```

So if I'm just able to set the environment variable ${CLOUDSMITH_KEY} to "basic" my problem is solved.

```
version: 2
updates:
  - package-ecosystem: "pip"
  ...
    env:
      CLOUDSMITH_KEY: basic
  ...
```

Unfortunately it's unsupported:

<img width="911" alt="Screen Shot 2022-01-24 at 3 28 54 PM" src="https://user-images.githubusercontent.com/82410520/150882352-20ccc5f1-9ff3-4a21-9644-63d7e42d3295.png">

Is there another way around this, or am I missing something?  I would have thought setting some environment variables was a common use-case.

**Comment by nwalsh1995** [comment]
I have the same issue. The local paths in our dependency files are relative to the top level folder and not the project folder. Dependabot assumes the paths are relative to the project folder so it cannot follow dependencies. We can solve this issue because Python pip `requirements.txt` supports environment variables. So we specify the environment variable different for local dev and another for dependabot execution. This maintains compatibility with the two workflows if environment variables could be supported.

**Comment by davidblewett** [comment]
As another point: we're hitting an issue where Dependabot can't correctly handle a Rust dependency via Cargo's Git implementation. We need to be able to set this: https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli , but can't due to missing environment variables for Dependabot.

**Comment by Vadorequest** [comment]
In my case, I'd like to grant access to some of our ENV variables that are already set in the GitHub repo, that would be even better than duplicating those for Dependabot specifically.

**Comment by Vadorequest** [comment]
I found this article: https://danielabaron.me/blog/dependabot-secrets/#dependabot-secrets

And on my repo, I can set Dependabot secrets at https://github.com/UnlyEd/github-action-deploy-on-vercel/settings/secrets/dependabot

@trent-abc I believe this might solve your issue.

**Comment by jeffwidman** [comment]
Related:
* https://github.com/dependabot/dependabot-core/issues/3888

Although that one could also be solved by allowing passing in composer-specific config, or changing how we clone.

**Comment by felixlut** [comment]
Any status on this? Currently we are limited in our usage of Dependabot as it doesn't support ``Environment`` level secrets and variables.

**Comment by AArnott** [comment]
I'm getting repeated complaints (like https://github.com/dotnet/Nerdbank.GitVersioning/issues/1234 and https://github.com/dotnet/Nerdbank.GitVersioning/issues/1192) that Dependabot breaks for repos that use Nerdbank.GitVersioning.

If Dependabot would allow setting environment variables, users could configure it to set `NBGV_GitEngine=Disabled` which would resolve the problem for 99% of the users.
Alternatively, Dependabot could document an environment variable that it already uniquely sets that NBGV could automatically respond to.

**Comment by flcdrg** [comment]
Good news from the Dependabot team - that PR linked ^^ should be setting `NBGV_GitEngine` now.. so I think we have a workaround!

**Comment by Cjewett** [comment]
Running Dependabot on a self-hosted runner using ARC is resulting in NBGV errors still. Were those fixes verified and rolled out?

Correct me if I'm wrong @AArnott but NBGV_GitEngine=Disabled should pretty much make it so nothing NBGV related runs? I've used that variable in other places with shallow clones and it seemed to work fine in those scenarios. Want to make sure errors such as `The "Nerdbank.GitVersioning.Tasks.SetCloudBuildVariables" task failed unexpectedly` shouldn't pop up in this Dependabot use case with the fix above though.

**Comment by AArnott** [comment]
@Cjewett I don't use Dependabot (any more) myself, but here's a guess: given your situation is self-hosted, maybe the environment variable change doesn't apply to you. But as a self-hosted agent, I bet it's because you have control over your own environment variables already, but have to make the change yourself.

**Comment by Cjewett** [comment]
@AArnott GitHub's Dependabot functionality allows you to provide a self-hosted runner but it requires that Docker exists so it can run the Dependabot updater tools as a container. I tried setting the environment variable on the self-hosted runner hoping that would fix it but still hit the same issues.

**Comment by Cjewett** [comment]
@brettfo @JamieMagee @rickreyhsig Possible one of you could chime in on the above? We're on the latest Nerdbank.GitVersioning using self-hosted Dependabot runners and the process fails because of the error @AArnott linked here: https://github.com/dependabot/dependabot-core/issues/4660#issuecomment-3170935213

We've set our self-hosted runner to include the NBGV_GitEngine=disabled env var as well and it's still failing.

**Comment by Cjewett** [comment]
After talking with GitHub support we determined the following:
- The fix mentioned in the previous post is not released. They were unsure when it would be released and were not receiving responses from the Dependabot team.
- You can't override the environment variables in if you're using GitHub's Dependabot integration. Even if you are using self-hosted runners setting the environment variable on the host itself doesn't work because containers are spun up to run these jobs. Probably some very hacky ways to approach the problem but we did not investigate.
- Nerdbank.GitVersioning cannot be turned off by setting <NBGV_GitEngine>Disabled</NBGV_GitEngine> in a .props file.

What you can do though is stop Nerdbank.GitVersioning from being included as a package during the `dotnet restore` process by wrapping it with something like below. That has unblocked us and we're at least able to start running SCA scans again.
```
<Project>
  <ItemGroup Condition="'$(DEPENDABOT)' != 'true'">
    <GlobalPackageReference Include="Nerdbank.GitVersioning" Version="3.5.119" />
  </ItemGroup>
</Project>
```

**Comment by AArnott** [comment]
Thanks, @Cjewett. Knowing that `DEPENDABOT` is set to true helps. That should allow nerdbank.gitversioning to come with a workaround built-in for this.

**Comment by AArnott** [comment]
@Cjewett and others: as of https://github.com/dotnet/Nerdbank.GitVersioning/pull/1284, Nerdbank.GitVersioning will automatically check for the DEPENDABOT environment variable and disable the git engine in that case.

**Comment by cristobal** [comment]
Having problems with this as well, the issue is that we have is the following:

## Dependabot NPM registry works fine
Doing:
```yaml
# Custom npm registry for ORG packages
registries:
  namespace-npm-registry:  # Name of your registry entry
    type: npm-registry
    url: https://pkgs.dev.azure.com/{ORG}/{TEAM}/_packaging/{namespace}/npm/registry/
    token: ${{secrets.DEPENDABOT_ADO_FEED_TOKEN}}
    replaces-base: false

  - package-ecosystem: npm
    directory: /apps/web
    ...
    registries:
      - azure-npm-registry
```

Works fine for the Dependabot part.

## PNPM update version
However we get an issue when corepack under the hood uses pnpm to update the package-lock.yaml, since pnpm is using .npmprc with env variable replacement:
```ìni
# default npm registry
registry=https://registry.npmjs.org

# scope scoped packages registry
@namespace:registry=https://pkgs.dev.azure.com/{ORG}/{TEAM}/_packaging/{namespace}/npm/registry/

; begin auth token
//pkgs.dev.azure.com/{ORG}/{TEAM}/_packaging/{namespace}/npm/registry/:username=bn-apps
//pkgs.dev.azure.com/{ORG}/{TEAM}/_packaging/{namespace}/npm/registry/:_password=${ADO_FEED_TOKEN}
//pkgs.dev.azure.com/{ORG}/{TEAM}/_packaging/{custom-path}/npm/registry/:email=...
; end auth token
```

The secrets for Dependabot have been set correctly, however only the one used in the dependabot.yml file is take into account:
<img width="1000" height="448" alt="Image" src="https://github.com/user-attachments/assets/141ef7be-421d-4c29-b4a3-1018013e72d9" />

Since when dependabot finds an update and it tries to run pnpm via corepack and update the package-lock.jons, it fails todo so since it does not have access to the encoded `ADO_FEED_TOKEN`. Making it fail to update the pnpm-lock.yaml file and we see the following output:
<img width="1028" height="126" alt="Image" src="https://github.com/user-attachments/assets/67b13e04-a07d-45e9-9c9f-9424e447fdf1" />

## Frustrating
This is kind of frustrating that one can not rely upon Dependabot for package updates when used with private packages that are not in github registries since only the GITHHUB_TOKEN is available in the run 🤷🏽

<img width="631" height="315" alt="Image" src="https://github.com/user-attachments/assets/a9a05ddf-b97b-4133-a3e5-8a8fd78ecfb6" />

I never had this problem when using Renovate for package updates with private registries, which i used at my previous work.

At my current work now, they want use to rely on Dependabot for this work, however things do not work as one would exepect here:
1. We will try to move our things to github private registries 
2. But if the problem still persistewe may need to move to other solutions like Renovate. 

Cant really fathom that this issue is about 4 years old and nothing has been done here...
